name: Sync to Hugging Face Hub

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push -f https://Lander2007:$HF_TOKEN@huggingface.co/spaces/mohamed-waled-mohamed-ahmed/king-store-backend1 HEAD:main
